### ISSUE TITLE
Crashing in newer versions

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1637]
I haven't had any issues until sometime around 7.2-2 or so, but I can't remember exactly.

I'm getting random crashes. I have a schedule running with very basic sequences. Sometimes it will crash within a few hours. Other times I'll go a day or two until a crash. The crash times don't correspond to a start or end to the schedule. The player continues to run after the crash.

I was playing via the schedule using a sequence. I then created a playlist and used that playlist in the schedule, with the same results. I tried this because I've had an additional crash when trying to play a video directly from the Status page. The videos play once, then it crashes every time. Never repeats and just crashes. When I add the video to a playlist and play the playlist on repeat, no crashes. So, that's why I tried a playlist in the schedule after trying a sequence in the schedule.

Looking at the crash log, the Zoom Room figured it was crash code 11, but all we could find it that might be a file name issue. All files were checked and all are clean.

I turned on debug for the included crash logs.

CRASH LOGS: https://mccoycloud.com/index.php/s/bBqtaDkNM5eYjPg
FPP LOGS: https://mccoycloud.com/index.php/s/8ySGgJjrwSnLwab

**Comment by McCoyCOREUSA** [comment]
I crashed again. Do you want additional crash reports?

**Comment by Kryptonit3** [comment]
Same here. Two RPi 4Bs, one Player one Remote. First time setting up a remote and a player. I updated the one thats been working to the most recent branch and now FPPD keeps stopping. The device randomly becomes unreachable 

6925ea6 is the branch they are on. Need to figure out how to downgrade. Seems to only affect the device that is set as a Remote. I set it back to a player and now it is working again.

**Comment by McCoyCOREUSA** [comment]
UPDATE: The only thing I could think of that changed (other than updates) is that I added the Remote Falcon Monitor plugin. That plugin was not fully setup, since I can't get into my Kulp account and support hasn't responded. So, the plugin was just installed and not used/activated. 

I uninstalled the plugin and so far I have not had any crashes!

**Comment by McCoyCOREUSA** [comment]
UPDATE: I had another crash. Logs with 'debug' on for Command, MediaOut, Schedule, and Sequence -- via request by Daryl C.

CRASH LOGS: https://mccoycloud.com/index.php/s/ZWAkc6sKdkadXPC

**Comment by darylc** [comment]
Thanks, with this log I can see right before it crashed, it was trying to start playing Santa pre-season announcement MP3.mp3

I can't tell why it crashed though.

If I had a powered USB hub handy I'd use that between my Pi and Soundblaster play 3 to rule out some sort of power issue on the usb audio, but thats a wild stab in the dark really based on seeing 'SDLHotplugALSA'  Maybe (and I'm guessing) that hotplug means the soundblaster went away and came back?

**Comment by McCoyCOREUSA** [comment]
Thanks, Daryl. I've added a powered USB hub and will wait to see if this works.

**Comment by McCoyCOREUSA** [comment]
Daryl, another crash. This was with the powered USB hub between the Pi and the Soundblaster Play 3.

CRASH LOG: https://mccoycloud.com/index.php/s/Zdw6NtY9wcF8Mba

**Comment by andrew-busbee** [comment]
Not sure if it will help narrow down the above issue or just be a distraction, but I am seeing crashes anytime I repeat an mp3 audio file.  I saw above that your crashed when it was starting to play an mp3 file.  This is for FPP 7.3, and I also have a soundblaster usb connected.

If on the status page I select an mp3 file from the dropdown and toggle repeat, when it finishes the song it crashes and does not repeat the song.  No issue when I select a full sequence with audio and repeat it.  

I tried it with and without the soundblaster installed, and it crashed each time. :(

**Comment by McCoyCOREUSA** [comment]
Andrew, I found basically the same issue. Very interesting.

When I tried to manually play a video on FPP remotes, it works. When I manually select the repeat then play the video, it crashes after the first play every time. So, I put the video file in a playlist and when I play the playlist (with repeat set), it loops just fine with no crashing. Same video file. Only difference was it was playing via a playlist with immediate repeat instead of manually from the status page.

I though perhaps this was the same or similar issue. I originally had the scheduler playing a single sequence on repeat. It would play and repeat for hours, then the crash report (but FPP kept playing). I created a playlist with the one sequence and repeat, then set that in the scheduler (thinking it may be the same issue as the video), but it continues to crash.

My crashing is happening on a 15-second sequence that repeats. So, it plays and repeats for hours without any issues. But then crashes at some point. I can go a day or two before a crash. Sometimes I get two crashes in the same day just a few hours apart. I just can't find any logic to it.

**Comment by cpinkham** [comment]
> When I tried to manually play a video on FPP remotes, it works. When I manually select the repeat then play the video, it crashes after the first play every time. So, I put the video file in a playlist and when I play the playlist (with repeat set), it loops just fine with no crashing. Same video file. Only difference was it was playing via a playlist with immediate repeat instead of manually from the status page.

If you were selecting a video file on the main status page and then playing that file in repeat mode, then this sounds like the issue that was just fixed in the master branch in 599941df95a    The bug was affecting playing media files from the status page.  In the fppd daemon, this auto-generates a playlist and there was an issue when that auto-generated playlist would try to repeat.

**Comment by McCoyCOREUSA** [comment]
So far, v7.3.3 hasn't crashed. Been over 24 hours. FYI

**Comment by darylc** [comment]
Please test the very latest 7.3.x, Dan has fixed numerous crashes in that in the past few days.

**Comment by McCoyCOREUSA** [comment]
Latest FPP. Still crashing...

CRASH REPORT: https://mccoycloud.com/index.php/s/pMTH4ReGkxptY9R

**Comment by dkulp** [comment]
@McCoyCOREUSA - my gut feeling is that you have either a corrupt fseq file or your SD card is dying:

```
2023-11-19 12:46:45.320 (1817) [General] /opt/fpp/src/fppd.cpp:266: Crash handler called:  11
2023-11-19 12:46:45.392 (18372) [Sequence] /opt/fpp/src/Sequence.cpp:183: Problem reading frame 4:   A617AE78    Time: 71 ms     Last: 3     Lock: 0   GetFrame: 71   Unlock: 0
2023-11-19 12:46:48.943 (1817) [General] /opt/fpp/src/fppd.cpp:247: Stack: 
```

**Comment by McCoyCOREUSA** [comment]
I only have two 15-second sequences (one for daytime and one at night). The day sequence is audio only sequence. It plays and repeats constantly without issue, until something happens that causes this crash. FPP remains running and playing, however. I can go a few hours or a few days without a crash. I don't see any logic to it.

I've re-rendered the sequences and re-uploaded a few times, too.

I have not replaced the card, so I can try that.

**Comment by McCoyCOREUSA** [comment]
New SD card. Re-rendered and all uploaded. Tested and ran scheduled playlist and ran for about 24 hours fine, then just now crashed.

CRASH LOG: https://mccoycloud.com/index.php/s/tAopxKBT9zkefHT

**Comment by corcorpj** [comment]
This seems related, but I am running (3) Raspberry Pis with Multi-Sync.

My Main 'Player' controller is crashing with audio playback - adding a clip of the FPPD log for some context - 

`2023-12-07 18:57:09.868 (4674) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:1149: Audio has stalled   0
2023-12-07 18:57:10.166 (8518) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:273: Stalled audio, buffers still filling.
2023-12-07 18:57:10.689 (4674) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:1149: Audio has stalled   0
2023-12-07 18:57:10.944 (8518) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:273: Stalled audio, buffers still filling.
2023-12-07 18:57:11.553 (4674) [MediaOut] /opt/fpp/src/mediaoutput/SDLOut.cpp:1149: Audio has stalled   0`

After a whole bunch of these records - I start to see SLOW output warnings:
`2023-12-07 19:00:10.999 (9932) [ChannelOut] /opt/fpp/src/channeloutput/channeloutputthread.cpp:212: SLOW Output Thread: Loop: 50000us, Send: 112826us, Read: 77us, Process: 16us, FrameNum: 2174`

And finally - 
`2023-12-07 19:01:31.369 (8518) [General] /opt/fpp/src/fppd.cpp:265: Crash handler called:  11
2023-12-07 19:01:38.109 (8518) [General] /opt/fpp/src/fppd.cpp:273:   /opt/fpp/src/fppd() [0x19fdc]
2023-12-07 19:01:38.948 (8518) [General] /opt/fpp/src/fppd.cpp:273:   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x76452900]`


The crashes I am seeing have happened (2) times this season, hundreds of hours apart. My only best guess is a very small memory leak bubbling over - though the crash dumps do not snapshot system resource loads so hard to say.

**Comment by dkulp** [comment]
This is LIKELY fixedin 7.3.6.   We identified several small/slow memory leaks and fixed them in 7.3.6.

**Comment by ghormann** [comment]
Closing as no action in 30 days.  believe flixed in the latest 7.x branch.
