### ISSUE TITLE
Enhancement request: Broadcast playing music via icecast or soutcast

### ISSUE THREAD

**Issue by priyankchouksey** [FalconChristmas/fpp#467]
Here I would like to suggest a new features

Can the playing music be also broadcast through icecast/soutcast internet stream. The current method of broadcasting via FM is not sufficient (most new phones does not have radio in mobile) as people can only listen while in car and we don't want people to block the street. broadcasting over internet will allow people to listen over earphones.

Relevant material can be found here, https://www.smarthomebeginner.com/icecast-ices2-music-server-for-raspberry-pi-raspberry-pi-streaming-audio-server/

**Comment by nmiller0113** [comment]
1) I believe there is already a plugin for this, not 100% sure, but look at the plugin repo in FPP.  2) Be aware that this will never, ever be in sync with your show no matter what you do....all devices will vary so even if you put delays in your lights the music will still be off for any internet stream as distance to server and will play a role in delays...also, remember that putting delays in for internet streaming will make the time off for everyone listening over the radio.  There is absolutely no way to make this sync for everyone through multiple audio output options...the light will always be fixed in timing since it can never be "per user" like video.  Just some thoughts in case you weren't thinking of this.  Most people use the audio streaming online to do things outside of their lights...as a during the day option as an example.

**Comment by nmiller0113** [comment]
And here ya go!  https://falconchristmas.com/forum/index.php/topic,10064.0.html

**Comment by sslupsky** [comment]
@priyankchouksey Did you ever look further into using Icecast with FPP for real time broadcasting the show audio over wifi?  I had a look at the After Hours plugin referenced above but it is really not a real time streaming plugin.  Icecast seems like it would work well for this application.

**Comment by jcrossbdn** [comment]
After hours plug-in was designed to bring in music so yeah that won’t work for your application.

The problem with streaming out is the delay.  There is no way to sync the music up and have it reach the end user at the same time as the lights fire.  Streams have to buffer so you cannot win with this and if you start three streams on three phones right beside each other they will all be in different “time zones”.

This is why almost all of us use fm transmitters.  Bluetooth is starting to get closer but is still not adequate (especially if you have lip synced elements).

If your show can handle 5-10 seconds of delay between lights and audio then I’d say play with it and if you get it working share your setup with the community so others may benefit from your research.

Jason

**Comment by sslupsky** [comment]
Yeah, I looked further into Icecast and you are correct, latency can run up to 10 sec.  It appears WebRTC has a latency of about 500 msec which is a lot better but likely still not good enough to maintain sync with the lights.
